version: '{build}'

image: Visual Studio 2019

pull_requests:
  do_not_increment_build_number: true
  
branches:
  only:
  - master
  - develop

nuget:
  disable_publish_on_pr: true

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

install:
  - ps: dotnet tool install --global Cake.Tool --version 0.34.1

configuration: Release

build_script:
  - ps: dotnet cake build.cake --bootstrap
  - ps: dotnet cake build.cake --pack

assembly_info:
  patch: false
  
skip_commits:
  files:
    - LICENSE
    - README.md

test: on

artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet
- path: .\Artifacts\**\*.xml
  name: xUnit Test Results

deploy:
- provider: NuGet
  server: https://www.myget.org/F/nsarris/api/v2/package
  api_key:
    secure: oCcFfuNnxI4ng/H0WAIBxyD/3UisznKgApuMgBZlC99fINvj1l6CH0UeKCN25uJi
  skip_symbols: true
  on:
    branch: develop
- provider: NuGet
  name: production
  api_key:
    secure: Xnmi7G3a+NqP0A7Fmyej32H/tTknfpGVMuqGtHw8SXYDxaGipBsffx7Qa+XF8EIM
  on:
    branch: master
    appveyor_repo_tag: true
