version: '{build}'

image: Visual Studio 2019

pull_requests:
  do_not_increment_build_number: true
  
branches:
  only:
  - master
  - develop

nuget:
  disable_publish_on_pr: true

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

install:
  - ps: dotnet tool install --global Cake.Tool --version 0.34.1

build_script:
  - ps: dotnet cake build.cake --bootstrap
  - ps: dotnet cake build.cake --pack

assembly_info:
  patch: false
  
skip_commits:
  files:
    - LICENSE
    - README.md

#tests run manually in cake script to allow xml results to be uploaded in build artifacts
#set to on and run build script with --notests to have appveyor run the tests and handle results
test: off

artifacts:
#nuget artifacts uploaded in cake script in order to skip package artifacts on pull request builds
#enable below and remove the "PublishAppVeyorArtifacts" task to have appveyor handle nuget artifacts
#- path: .\artifacts\**\*.nupkg
#  name: NuGet
- path: .\Artifacts\**\*.xml
  name: xUnit Test Results

deploy:
- provider: GitHub
  release: v$(appveyor_build_version)
  tag: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: qG46z/8GOmuJx4VZKdMy7l1XPC+CRmXIV8t7uDIUxpPny0YG2y0UKAn+NAYEBz4O
  artifact: /.*\.nupkg/
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
- provider: GitHub
  release: v$(APPVEYOR_BUILD_VERSION)
  auth_token:
    secure: DNoZGQZLXHA3ng7jbMAzvEzWJtU56Jqqh45Bs312Fzl7kpxaGF0uf2KmyOHaLNeH
  artifact: /.*\.nupkg/
  draft: false
  prerelease: true
  on:
    branch: develop
- provider: NuGet
  name: production
  api_key:
    secure: 1CRLLqZLlLYXQrfEqK9sc1ipWskCSyEAIn8iG1Yqr9UhlUJWEJ5blPSqiWhzNOaI
  skip_symbols: true
  on:
    branch: master
    appveyor_repo_tag: true
- provider: NuGet
  server: https://www.myget.org/F/nsarris/api/v2/package
  symbol_server: https://www.myget.org/F/nsarris-citest/symbols/api/v2/package
  api_key:
    secure: oCcFfuNnxI4ng/H0WAIBxyD/3UisznKgApuMgBZlC99fINvj1l6CH0UeKCN25uJi
  skip_symbols: false
  on:
    branch: develop

for:
- branches:
    only:
      - master

  skip_non_tags: true	

- branches:
    only:
      - develop

  skip_tags: true	
