namespace TranslitSharp
{
    public static class TransliteratorConfigurationExtensions
    {
        public static TransliteratorConfiguration ConfigureGreekToLatin(this TransliteratorConfiguration configuration)
            => configuration
                .AddCharacterMap("Α", "A")
                .AddCharacterMap("Ά", "A")
                .AddCharacterMap("Β", "V")
                .AddCharacterMap("Γ", "G")
                .AddCharacterMap("Δ", "D")
                .AddCharacterMap("Ε", "E")
                .AddCharacterMap("Έ", "E")
                .AddCharacterMap("Ζ", "Z")
                .AddCharacterMap("Η", "I")
                .AddCharacterMap("Ή", "I")
                .AddCharacterMap("Θ", "TH")
                .AddCharacterMap("Ι", "I")
                .AddCharacterMap("Ϊ", "I")
                .AddCharacterMap("Ί", "I")
                .AddCharacterMap("ΐ", "i", map => map.AddAllCasePermutations = false)
                .AddCharacterMap("Κ", "K")
                .AddCharacterMap("Λ", "L")
                .AddCharacterMap("Μ", "M")
                .AddCharacterMap("Ν", "N")
                .AddCharacterMap("Ξ", "X")
                .AddCharacterMap("Ο", "O")
                .AddCharacterMap("Ό", "O")
                .AddCharacterMap("Π", "P")
                .AddCharacterMap("Ρ", "R")
                .AddCharacterMap("Σ", "S")
                .AddCharacterMap("ς", "s", map => map.AddAllCasePermutations = false)
                .AddCharacterMap("Τ", "T")
                .AddCharacterMap("Υ", "Y", map => map.Handler = GreekYpsilonTransliterationTokenHandler.Instance)
                .AddCharacterMap("Ύ", "Y", map => map.Handler = GreekYpsilonTransliterationTokenHandler.Instance)
                .AddCharacterMap("Ϋ", "Y", map => map.Handler = GreekYpsilonTransliterationTokenHandler.Instance)
                .AddCharacterMap("ΰ", "y", map => { map.Handler = GreekYpsilonTransliterationTokenHandler.Instance; map.AddAllCasePermutations = false; })
                .AddCharacterMap("Φ", "F")
                .AddCharacterMap("Χ", "CH")
                .AddCharacterMap("Ψ", "PS")
                .AddCharacterMap("Ω", "O")
                .AddCharacterMap("Ώ", "O")
                .AddCharacterMap("ΟΥ", "OU")
                .AddCharacterMap("ΟΎ", "OU")
                .AddCharacterMap("ΌΎ", "OU")
                .AddCharacterMap("Ό" + "Υ", "OU")
                .AddCharacterMap("ΜΠ", "MP", map => map.Handler = GreekMpTransliterationTokenHandler.Instance)
                .AddCharacterMap("ΓΓ", "NG")
                .AddCharacterMap("ΓΧ", "NCH")
                .AddCharacterMap("ΓΞ", "NX");
        
        public static TransliteratorConfiguration ConfigureLatin1SupplementToLatin(this TransliteratorConfiguration configuration)
            => configuration
                .AddCharacterMap("À", "A")
                .AddCharacterMap("Á", "A")
                .AddCharacterMap("Â", "A")
                .AddCharacterMap("Ã", "A")
                .AddCharacterMap("Ä", "A")
                .AddCharacterMap("Å", "A")
                .AddCharacterMap("Æ", "A")
                .AddCharacterMap("Ç", "C")
                .AddCharacterMap("È", "E")
                .AddCharacterMap("É", "E")
                .AddCharacterMap("Ê", "E")
                .AddCharacterMap("Ë", "E")
                .AddCharacterMap("Ì", "I")
                .AddCharacterMap("Í", "I")
                .AddCharacterMap("Î", "I")
                .AddCharacterMap("Ï", "I")
                .AddCharacterMap("Ð", "E")
                .AddCharacterMap("Ñ", "N")
                .AddCharacterMap("Ò", "O")
                .AddCharacterMap("Ó", "O")
                .AddCharacterMap("Ô", "O")
                .AddCharacterMap("Õ", "O")
                .AddCharacterMap("Ö", "O")
                .AddCharacterMap("Ø", "O")
                .AddCharacterMap("Ù", "U")
                .AddCharacterMap("Ú", "U")
                .AddCharacterMap("Û", "U")
                .AddCharacterMap("Ü", "U")
                .AddCharacterMap("Ý", "Y")
                .AddCharacterMap("Þ", "P")
                .AddCharacterMap("ß", "S", map => map.AddAllCasePermutations = false);
    }
}
